name: FrankChiaramonte
favicon: null
layout_spectrum: 0.5068845737259835
typography_spectrum: 0.30435671377927065
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5618915271479636
  lightness: 0.4944140906445682
  saturation: 0.32831936818547547
  rhythmicContrast: 0.31187186297029257
purpose: []
