layout_spectrum: 0.9350759
favicon: null
name: FrankChiaramonte
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.5618915271479636
  saturation: 0.3283193681854755
  brandColors:
    - '#f7fffd'
    - '#0b0c07'
    - '#423f38'
    - '#847f59'
    - '#b4cef1'
  lightness: 0.4944140906445682
  rhythmicContrast: 0.3118718629702926
typography_spectrum: 0.3043567137792706
