color:
  brandStrength: 0.2023609
  saturation: 0.5168634
  brandColors:
    - '#432E19'
    - '#FDFFFF'
    - '#B3815B'
    - '#FFD79B'
    - '#92B5F1'
  lightness: 0.5042158
  rhythmicContrast: 0.4915683
analytics:
  facebook: null
  google: null
  twitter: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  version: null
  bucket: null
favicon: null
layout_spectrum: 0.9072512
purpose: []
name: FrankChiaramonte
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1408094
