layout_spectrum: 0.9072512
favicon: null
name: FrankChiaramonte
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  bucket: null
  version: null
  domain: null
color:
  brandStrength: 0.5618915271479636
  saturation: 0.3283194
  brandColors:
    - '#432E19'
    - '#FDFFFF'
    - '#B3815B'
    - '#FFD79B'
    - '#92B5F1'
  lightness: 0.5952783
  rhythmicContrast: 0.2613828
typography_spectrum: 0.1408094
